import './globals.css'
import Navigation from 'seiodm/Navigation/Navigation'
import { Montserrat } from '@next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';




export const metadata = {
  title: 'SEIODM',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  subsets:['latin'],
  weight:['400','700'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
           <head>
        <title>SEIODM</title>
      </head>
      <body>
        <main className={montserrat.className}>
        <Navigation />
        {children}
        </main>
                 
      </body>
    </html>
  )
}
